vim.g.mapleader = " "
vim.g.maplocaleader = " "
vim.o.clipboard = "unnamedplus"
vim.o.number = true
vim.o.relativenumber = true
vim.o.signcolumn = "yes"
vim.o.tabstop = 4
vim.o.shiftwidth = 4
vim.o.updatetime = 50
vim.o.termguicolors = true
vim.o.mouse = "a"
vim.o.timeoutlen = 250
vim.o.smartindent = true
vim.o.cursorline = true
vim.o.swapfile = false
