vim.g.mapleader = " "
vim.g.maplocaleader = " "
vim.o.clipboard = "unnamedplus"
vim.o.number = true
vim.o.relativenumber = true
vim.o.signcolumn = "yes"
vim.o.tabstop = 4
vim.o.shiftwidth = 4
vim.o.termguicolors = true
vim.o.mouse = "a"
vim.o.timeoutlen = 250
vim.o.smartindent = true
vim.o.cursorline = true
vim.o.swapfile = false
vim.o.timeoutlen = 100
vim.o.updatetime = 50
vim.o.conceallevel = 2
vim.o.encoding = "utf-8"
vim.o.fileencoding = "utf-8"
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.scrolloff = 8
vim.o.foldcolumn = "1"
vim.o.foldlevel = 99
vim.o.foldlevelstart = 99
vim.o.foldenable = true
